version: 2
jobs:
  build:
    working_directory: /root/go/src/github.com/upvalue/meditations
    branches:
      only:
        - master

    docker:
      - image: ubuntu:latest
        environment:
          GOPATH: /root/go
          GO111MODULE: "on" # "on" without quotes is apparently true in YAML. cool.

    steps:
      - run:
          name: Install dependencies
          command: apt update && apt install -y nodejs build-essential stow git npm wget 

      # We need go 1.11 for modules
      - run:
          name: Install golang from binary
          command: |
            cd /tmp
            wget https://dl.google.com/go/go1.11.linux-amd64.tar.gz
            tar -xf go1.11.linux-amd64.tar.gz
            mkdir -p /usr/local/stow
            mv go /usr/local/stow
            cd /usr/local/stow
            stow go

      - checkout

      - run:
          name: Set environment variables
          command: |
            echo 'export PATH=/root/go/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - run:
          name: Run golang backend tests
          command: cd /root/go/src/github.com/upvalue/meditations && go test -cover -v -race $(go list ./... | grep -v /vendor/)

      - run:
          name: Install npm dependencies
          command: npm install --ignore-scripts

      - run:
          name: Run React frontend tests
          command: npm run test-frontend
